version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: webpack-node-externals
    versions:
    - 2.5.2
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: unist-util-visit
    versions:
    - 2.0.3
  - dependency-name: escape-string-regexp
    versions:
    - 4.0.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
